import React, { useMemo, useState } from 'react';
import { useLocation } from 'wouter';
import { Activity, AlertTriangle, Ambulance, ArrowLeft, Bell, ChevronRight, CircleDot, Clock3, Flame, Gauge, Hospital, LayoutGrid, Map, MessageSquare, MoreHorizontal, Navigation, Phone, Radio, Settings, Shield, Siren, Truck, Users, X, Zap } from 'lucide-react';
import { Toaster, toast } from 'sonner';

/* Aegivault mobile app direction: quiet dark graphite, signal yellow, rescue red, cyan navigation, safety green. Simulation only. */
const incidentsSeed=[
 {id:'INC-1042',type:'FIRE',title:'Industrial Area fire',location:'Lusaka Road · 0.8 km',severity:'CRITICAL',time:'2 min ago',status:'ACTIVE',icon:Flame,color:'red',units:['F-07','AMB-12'],desc:'Multiple reports of smoke from a warehouse block. Wind moving east. Perimeter requested.'},
 {id:'INC-1041',type:'MEDICAL',title:'Multi-vehicle collision',location:'Mombasa Rd · 2.4 km',severity:'HIGH',time:'8 min ago',status:'DISPATCHED',icon:Ambulance,color:'yellow',units:['AMB-07'],desc:'Three vehicles involved. Traffic blocked in both directions. Two patients reported.'},
 {id:'INC-1038',type:'SECURITY',title:'Crowd incident',location:'CBD · 4.1 km',severity:'MEDIUM',time:'14 min ago',status:'MONITORING',icon:Shield,color:'cyan',units:['POL-22'],desc:'Crowd density increasing near the transit interchange. Police unit observing.'},
 {id:'INC-1037',type:'FLOOD',title:'Roadway flooding',location:'South B · 5.8 km',severity:'LOW',time:'21 min ago',status:'MONITORING',icon:Truck,color:'green',units:[],desc:'Water crossing the lower roadway. Public works notified.'}
];
const units=[['AMB-07','Ambulance','Available','4.2 km','6 min',Ambulance,'cyan'],['AMB-12','Ambulance','Deployed','0.8 km','2 min',Ambulance,'red'],['F-07','Fire engine','Deployed','0.9 km','3 min',Flame,'red'],['POL-22','Police unit','Available','3.5 km','8 min',Shield,'yellow'],['R-03','Rescue team','Available','6.1 km','12 min',Truck,'green']];
const hospitals=[['Hospital Alpha','Emergency department','82%','11 beds','2.1 km','green'],['St. Mary Trauma Centre','Trauma + ICU','91%','2 beds','5.6 km','yellow'],['Eastlands Medical','Emergency department','48%','18 beds','7.4 km','cyan']];
function Badge({children,tone='neutral'}){return <span className={`badge ${tone}`}>{children}</span>}
function AppHeader({onBell}){return <header className="app-top"><div className="app-brand"><div className="vault-mark"><span></span><span></span><span></span></div><div><b>AEGIVAULT</b><small>OPS / NAIROBI</small></div></div><div className="top-actions"><span className="live-indicator"><i/>LIVE</span><button className="round-icon" onClick={onBell}><Bell size={18}/><em>3</em></button></div></header>}
function BottomNav({screen,setScreen}){return <nav className="bottom-nav">{[['command',LayoutGrid,'Command'],['incidents',Siren,'Incidents'],['map',Map,'Map'],['units',Users,'Units'],['more',MoreHorizontal,'More']].map(([id,Icon,label])=><button className={screen===id?'active':''} onClick={()=>setScreen(id)} key={id}><Icon size={19}/><span>{label}</span></button>)}</nav>}
function MiniMap({large=false}){return <div className={`mini-map ${large?'large-map':''}`}><div className="map-grid"/><div className="map-road r1"/><div className="map-road r2"/><div className="map-road r3"/><div className="map-water"/><div className="map-label l1">INDUSTRIAL AREA</div><div className="map-label l2">LUSAKA RD</div><div className="map-pin critical"><Flame size={13}/></div><div className="map-pin unit-one"><Ambulance size={12}/></div><div className="map-pin unit-two"><Truck size={12}/></div><div className="map-ring"/></div>}
function Stat({label,value,sub,tone='cyan',icon:Icon}){return <div className={`stat-card ${tone}`}><div className="stat-head"><span>{label}</span>{Icon&&<Icon size={15}/>}</div><strong>{value}</strong><small>{sub}</small></div>}
function IncidentRow({item,onOpen}){const Icon=item.icon; return <button className="incident-row" onClick={()=>onOpen(item)}><div className={`incident-icon ${item.color}`}><Icon size={18}/></div><div className="incident-info"><div><b>{item.id}</b><Badge tone={item.color}>{item.severity}</Badge></div><h3>{item.title}</h3><p>{item.location}</p></div><div className="incident-side"><span>{item.time}</span><ChevronRight size={16}/></div></button>}
function Command({incidents,onOpen,setScreen}){const active=incidents.filter(i=>i.status==='ACTIVE'||i.status==='DISPATCHED').length; return <div className="screen command-screen"><div className="screen-intro"><div><p className="kicker">Thursday · 30 Aug 2026</p><h1>Good evening,<br/><em>Commander.</em></h1></div><Badge tone="green"><i/> Simulation mode</Badge></div><div className="command-alert"><div className="alert-icon"><Radio size={18}/></div><div><b>System nominal</b><span>All services responding within threshold</span></div><Activity size={18} className="alert-activity"/></div><div className="stat-grid"><Stat label="Active incidents" value={active} sub="2 need action now" tone="red" icon={Siren}/><Stat label="Units deployed" value="08" sub="of 42 available" tone="yellow" icon={Ambulance}/><Stat label="Response time" value="6.4m" sub="−18% from baseline" tone="cyan" icon={Clock3}/></div><div className="section-header"><div><p className="kicker">Operational picture</p><h2>Live field view</h2></div><button onClick={()=>setScreen('map')} className="link-button">Full map <ChevronRight size={15}/></button></div><MiniMap/><div className="section-header incidents-head"><div><p className="kicker">Needs attention</p><h2>Active incidents <span>{active}</span></h2></div><button onClick={()=>setScreen('incidents')} className="link-button">View all <ChevronRight size={15}/></button></div><div className="incident-list">{incidents.slice(0,3).map(i=><IncidentRow item={i} onOpen={onOpen} key={i.id}/>)}</div></div>}
function Incidents({incidents,onOpen}){const [filter,setFilter]=useState('ALL');const shown=incidents.filter(i=>filter==='ALL'||i.severity===filter);return <div className="screen"><div className="screen-title-row"><div><p className="kicker">Incident management</p><h1>Situational<br/><em>awareness.</em></h1></div><button className="round-icon"><SlidersIcon/></button></div><div className="filter-row">{['ALL','CRITICAL','HIGH','MEDIUM'].map(f=><button className={filter===f?'selected':''} key={f} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="incident-list full-list">{shown.map(i=><IncidentRow item={i} onOpen={onOpen} key={i.id}/>)}</div></div>}
function SlidersIcon(){return <Gauge size={18}/>} 
function IncidentDetail({incident,onBack,onDispatch}){const [assigned,setAssigned]=useState(incident.status==='DISPATCHED');const Icon=incident.icon;return <div className="screen detail-screen"><button className="back-button" onClick={onBack}><ArrowLeft size={18}/> Incident overview</button><div className="detail-title"><div className={`incident-icon ${incident.color}`}><Icon size={24}/></div><div><p className="kicker">{incident.id} · {incident.type}</p><h1>{incident.title}</h1><p>{incident.location}</p></div></div><div className="priority-banner"><div><span>Priority assessment</span><b>{incident.severity}</b></div><Badge tone={incident.color}>{incident.status}</Badge></div><MiniMap large/><div className="detail-section"><div className="section-header"><div><p className="kicker">Dispatch recommendation</p><h2>Best available units</h2></div><Zap size={19} className="cyan-icon"/></div><div className="recommend-card"><div className="recommend-rank">01</div><div><b>AMB-07 · nearest capable unit</b><span>4.2 km away · ETA 6 min · Available</span></div><Badge tone="green">RECOMMENDED</Badge></div><button className={`primary-button ${assigned?'assigned':''}`} onClick={()=>{setAssigned(true);onDispatch(incident);toast.success('Dispatch recorded in simulation')}}>{assigned?<><CircleDot size={18}/> Unit dispatched</>:<><Siren size={18}/> Dispatch recommended units</>}</button></div><div className="detail-section timeline"><div className="section-header"><div><p className="kicker">Immutable event history</p><h2>Timeline</h2></div></div>{[['18:42','Incident reported','System intake'],['18:43','Classified '+incident.severity,'Command triage'],['18:44','Recommendation generated','Dispatch engine'],['18:45','Awaiting operator action','Current state']].map((t,i)=><div className={`timeline-row ${i===3?'current':''}`} key={t[0]}><b>{t[0]}</b><i/><div><strong>{t[1]}</strong><span>{t[2]}</span></div></div>)}</div></div>}
function Units(){return <div className="screen"><div className="screen-title-row"><div><p className="kicker">Field resources</p><h1>Unit<br/><em>readiness.</em></h1></div><button className="round-icon"><Settings size={18}/></button></div><div className="availability"><div><strong>42</strong><span>total units</span></div><div className="availability-bar"><i style={{width:'68%'}}/><i style={{width:'18%'}}/><i style={{width:'14%'}}/></div><div className="availability-key"><span><i className="green-dot"/> Available 29</span><span><i className="red-dot"/> Deployed 8</span><span><i className="gray-dot"/> Offline 5</span></div></div><div className="unit-list">{units.map(([id,type,status,distance,eta,Icon,color])=><div className="unit-row" key={id}><div className={`unit-icon ${color}`}><Icon size={17}/></div><div className="unit-info"><b>{id}</b><span>{type} · {distance}</span></div><div className="unit-status"><Badge tone={status==='Available'?'green':status==='Deployed'?'red':'neutral'}>{status}</Badge><small>ETA {eta}</small></div></div>)}</div></div>}
function MapScreen({setScreen}){return <div className="screen map-screen"><div className="map-screen-head"><div><p className="kicker">GIS / Nairobi sector</p><h1>Field <em>map.</em></h1></div><Badge tone="cyan"><i/> 42 units</Badge></div><MiniMap large/><div className="map-legend"><span><i className="pin-red"/> Incidents</span><span><i className="pin-cyan"/> Responders</span><span><i className="pin-green"/> Hospitals</span></div><div className="map-actions"><button onClick={()=>setScreen('incidents')}><Siren size={17}/> Active incidents</button><button><Navigation size={17}/> Safe routes</button><button><Hospital size={17}/> Facilities</button></div><div className="facility-card"><div><Hospital size={18}/><div><b>Hospital Alpha</b><span>11 emergency beds · 2.1 km</span></div></div><Badge tone="green">82% capacity</Badge></div></div>}
function More(){return <div className="screen"><p className="kicker">System controls</p><h1>More<br/><em>capabilities.</em></h1><div className="more-grid">{[[MessageSquare,'Comms','Team channels'],[Hospital,'Hospitals','Capacity board'],[Gauge,'Simulation','Scenario controls'],[Shield,'Audit log','Immutable history'],[Phone,'Contacts','Response directory'],[Settings,'Settings','System preferences']].map(([Icon,title,sub])=><button key={title} onClick={()=>toast(`${title} module is ready for connection`)}><Icon size={20}/><b>{title}</b><span>{sub}</span><ChevronRight size={16}/></button>)}</div><div className="simulation-note"><AlertTriangle size={18}/><div><b>Simulation environment</b><span>This interface is a training and product demonstration tool. It is not certified for live emergency response.</span></div></div></div>}
export default function App(){const [path,setPath]=useLocation();const routeScreen=path==='/incidents'?'incidents':path==='/units'?'units':path==='/map'?'map':path==='/more'?'more':'command';const [screen,setScreenState]=useState(routeScreen);const setScreen=next=>{setScreenState(next);setPath(next==='command'?'/':`/${next}`)};const [incidents,setIncidents]=useState(incidentsSeed);const [selected,setSelected]=useState(null);const open=i=>{setSelected(i);setScreen('detail')};const dispatch=i=>setIncidents(xs=>xs.map(x=>x.id===i.id?{...x,status:'DISPATCHED',units:[...x.units,'AMB-07']}:x));const body=selected&&screen==='detail'?<IncidentDetail incident={selected} onBack={()=>setScreen('incidents')} onDispatch={dispatch}/>:screen==='command'?<Command incidents={incidents} onOpen={open} setScreen={setScreen}/>:screen==='incidents'?<Incidents incidents={incidents} onOpen={open}/>:screen==='units'?<Units/>:screen==='map'?<MapScreen setScreen={setScreen}/>:<More/>;return <div className="mobile-app"><AppHeader onBell={()=>toast('3 operational notifications')}/><div className="app-content">{body}</div><BottomNav screen={screen==='detail'?'incidents':screen} setScreen={setScreen}/><Toaster position="top-center" richColors/></div>}
